@author Lamon Santos
@version 1.0
@since 09/10/2023

public class JavaDoc{
    /**
     * Esse metodo serve para soma dois números inteiros
     *@param numeroUm //Este é o primeiro parâmetro de todos;
     *@param numeroDois //Este é o segundo parâmentro de todos;
     *@return int o resultado deste método é a soma dos numeros inteiros;
     */
      public int soma(int numeroUm, int numeroDois){
          return numeroUm + numeroDois;
      }
}